# Generated by Django 3.0.5 on 2020-04-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200420_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
